### ISSUE TITLE
"Add token" vs "Edit token whitelist"

### ISSUE THREAD

**Issue by bjornwgnr** [parity-js/fether#103]
Imo, it should say 'Add token' on both views.

<img width="364" alt="screen shot 2018-06-26 at 23 38 14" src="https://user-images.githubusercontent.com/17831185/41940729-0e434368-799a-11e8-85e2-4706dc65d774.png">
<img width="356" alt="screen shot 2018-06-26 at 23 38 04" src="https://user-images.githubusercontent.com/17831185/41940733-107f0342-799a-11e8-8412-71deb9a852ae.png">

**Comment by Tbaut** [comment]
You have the "add" in front of each token, I don't think it's necessary to have it in the title. 
I removed the "Edit" just to show "Token whitelist" in previous PR
