### ISSUE TITLE
Add Electron menubar

### ISSUE THREAD

**Issue by amaurymartiny** [parity-js/fether#16]
The idea proposed by @brianflanagan was to have a menubar-icon always visible.

I found this library which should simplify things https://github.com/maxogden/menubar.

Note: the transition to a Chrome extension will become super easy UI-wise.

**Comment by brianflanagan** [comment]
(Aside: the app is designed so it should also be able to work without modification as a small fixed-window non-menubar app. If there are compatibility issues, or usability issues with making it a menubar app, let's drop the idea. The UX is very similar in either case.)

**Comment by amaurymartiny** [comment]
Dropping the menubar app altogether.

It doesn't work on Gnome 3, doesn't display well on other linuxes. It'll bring overall more trouble than anything else.
