### ISSUE TITLE
Drag and drop crashes fether

### ISSUE THREAD

**Issue by 5chdn** [parity-js/fether#85]
Drag and drop of the loading indicator crashes fether beyond recovery.

![screenshot at 2018-06-25 10-44-54](https://user-images.githubusercontent.com/15729797/41840071-1b304c3c-7865-11e8-9c95-d4529aa3086d.png)

Latest master checked out this morning.

**Comment by amaurymartiny** [comment]
Afri is this reproducible on your machine?

**Comment by Tbaut** [comment]
Can't reproduce either (tried on syncing, TX sending, Waiting for node connection)

**Comment by Tbaut** [comment]
@5chdn ^

**Comment by 5chdn** [comment]
Yes, are you at the office?

**Comment by 5chdn** [comment]
Still happening with latest master from today.

![screenshot at 2018-06-29 12-12-51](https://user-images.githubusercontent.com/15729797/42087234-da8cad7c-7b95-11e8-87e5-a296abcf171d.png)

It completely crashes, even the logs in terminal stop running, and the parity process is `<defunct>`

**Comment by amaurymartiny** [comment]
Maybe this? https://github.com/electron/electron/issues/12820

@5chdn could your try, inside the `src/packages/fether-electron` folder, `yarn start --disable-gpu`?

**Comment by 5chdn** [comment]
It passes the flag to parity.

```
~/.opt/fether/packages/fether-electron master
❯ yarn electron --disable-gpu
yarn run v1.5.1
$ electron dist/main/main.js --disable-gpu
[2018-06-29T11:44:05.242Z] INFO (electron/21499 on alcor): Starting Fether...
[2018-06-29T11:44:05.312Z] INFO (electron/21499 on alcor): Parity found on machine, can be run with "parity".
[2018-06-29T11:44:08.350Z] INFO (electron/21499 on alcor): Running "parity --disable-gpu --light".
[2018-06-29T11:44:08.365Z] INFO (parity/21499 on alcor): error: Found argument '--disable-gpu' which wasn't expected, or isn't valid in this context

USAGE:
    parity [SUBCOMMAND]

For more information try --help

[2018-06-29T11:44:08.370Z] INFO (electron/21499 on alcor): Stopping parity.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c electron dist/main/main.js --disable-gpu
Directory: /home/user/.opt/fether/packages/fether-electron
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/user/.opt/fether/packages/fether-electron/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by amaurymartiny** [comment]
Ah yeah, forgot about that.

@5chdn I just built binaries (or you can pull the latest master) where I disabled gpu acceleration for linux. Tell me if that works.
